image: horgix/docker-make:latest

stages:
  - check
  - build
  - staging
  - production

check:
  stage: check
  script:
    - docker info

build:
  stage: build
  variables:
    CACHE_DIR:  "/cache/maven-repository"
    MAVEN_OPTS_DOCKER: '-e MAVEN_OPTS="-Dmaven.repo.local=/cache" -v ${CACHE_DIR}:/cache'
  script:
    - make build
    - docker login -u="${HUB_LOGIN}" -p="${HUB_PASSWORD}"
    - docker push horgix/click-count:${CI_BUILD_REF}

staging:
  stage: staging
  variables:
    ENVIRONMENT: "staging"
    ENDPOINT: "${STAGING_ENDPOINT}"
  script:
    - make staging
  environment: staging

production:
  stage: production
  variables:
    ENVIRONMENT: "prod"
    ENDPOINT: "${PRODUCTION_ENDPOINT}"
  script:
    - make production
  environment: production
