image: horgix/docker-make:latest

variables:
  BUILD_DIR:  "/tmp/gitlab-build-${CI_PIPELINE_ID}"

stages:
  - build
  - cleanup
  - staging
  - production

build:
  stage: build
  variables:
    CACHE_DIR:  "/cache/maven-repository"
    MAVEN_OPTS_DOCKER: '-e MAVEN_OPTS="-Dmaven.repo.local=/cache" -v ${CACHE_DIR}:/cache'
  script:
    - mkdir -p ${BUILD_DIR} && cp ${PWD}/. ${BUILD_DIR} -R
    - make build
    - docker login -u="${HUB_LOGIN}" -p="${HUB_PASSWORD}"
    - docker push horgix/click-count:${CI_BUILD_REF}

cleanup:
  stage: cleanup
  script:
    - rm -rf ${BUILD_DIR}
  when: always

staging:
  stage: staging
  variables:
    ENVIRONMENT: "staging"
    ENDPOINT: "${STAGING_ENDPOINT}"
    REDIS_HOST: "${STAGING_REDIS}"
  script:
    - make staging
  artifacts:
    paths:
      - marathon_app_staging.json
  environment: staging
  only:
    - tags

production:
  stage: production
  variables:
    ENVIRONMENT: "prod"
    ENDPOINT: "${PRODUCTION_ENDPOINT}"
    REDIS_HOST: "${PRODUCTION_REDIS}"
  script:
    - make production
  artifacts:
    paths:
      - marathon_app_prod.json
  environment: production
  only:
    - master
