image: horgix/docker-make:latest

stages:
  - check
  - build
  - staging

check:
  stage: check
  script:
    - docker info

build:
  stage: build
  script:
    - make build

staging:
  stage: staging
  script:
    - make staging
