image: horgix/docker-make:latest

stages:
  - check
  - build
  - staging

check:
  stage: check
  script:
    - docker info

build:
  stage: build
  script:
    - make build
    - docker login -u="${HUB_LOGIN}" -p="${HUB_PASSWORD}"
    - docker push horgix/click-count:${CI_BUILD_REF}

staging:
  stage: staging
  script:
    - make staging
